### ISSUE TITLE
Analysis & Design system

### ISSUE THREAD

**Issue by HoangNhu01** [HoangNhu01/stt30_HealthyDrinkShop_DACNPM#1]
Create required diagram

**Comment by HoangNhu01** [comment]
Complete usecase diagram
![339922186_617110823223853_4844289099972920542_n](https://user-images.githubusercontent.com/103115982/231076588-7ec11041-e8b0-4185-8991-bf3aeb8c75ef.jpg)

**Comment by thanhemon** [comment]
![image](https://user-images.githubusercontent.com/107067079/232520937-556ab7f5-0069-423d-83ef-111a4ee58b25.png)

**Comment by thanhemon** [comment]
entity relationship diagram

**Comment by thanhemon** [comment]
![image](https://user-images.githubusercontent.com/107067079/232522195-c105a122-feb5-499e-b866-046a9c8a264c.png)

Class diagram

**Comment by thanhemon** [comment]
![image](https://user-images.githubusercontent.com/107067079/232522423-18ae617a-3e99-4fd4-83e9-affee266997e.png)

Use case diagram

**Comment by thanhemon** [comment]
![image](https://user-images.githubusercontent.com/107067079/232522611-f6f576f2-23ee-4a41-97fd-21f73828e7c1.png)
![image](https://user-images.githubusercontent.com/107067079/232522663-bc88b197-da8a-4ad0-b0ba-20a8b0c0d3e6.png)
![image](https://user-images.githubusercontent.com/107067079/232522703-5bdcdad4-25c6-495e-afb1-6b182550b675.png)

activity diagram

**Comment by thanhemon** [comment]
![image](https://user-images.githubusercontent.com/107067079/232522889-117cc09c-4ece-4dce-a94d-ff3570458ffb.png)
sequence diagram

**Comment by thanhemon** [comment]
update usecase tổng quát
![image](https://user-images.githubusercontent.com/107067079/234183473-be4364d3-13c3-4303-b383-e66f52710418.png)

**Comment by thanhemon** [comment]
Usecase chi tiết loại sản phẩm
![image](https://user-images.githubusercontent.com/107067079/234183619-8d1d694f-8dec-485c-a68d-d0daa6286ef7.png)

**Comment by thanhemon** [comment]
Usecase chi tiết quản lý sản phẩm
![image](https://user-images.githubusercontent.com/107067079/234184443-a7d1a274-ec43-4e04-840f-bcee632f8ac5.png)

**Comment by thanhemon** [comment]
[vs.docx](https://github.com/HoangNhu01/HealthyDrinkShop_DACNPM/files/11427254/vs.docx)
full Analis & design
